-- Create products table
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY,
    name TEXT,
    description TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Insert 100 realistic products
INSERT INTO products (id, name, description, price) VALUES 
    (gen_random_uuid(), 'Tai nghe Sony WH-1000XM5', 'Chống ồn đỉnh cao, âm thanh trung thực.', 29296704),
    (gen_random_uuid(), 'Hạt điều rang muối (Bản giới hạn)', 'Món ăn vặt bổ dưỡng, giòn tan.', 104666),
    (gen_random_uuid(), 'Ấm đun siêu tốc Electrolux (New 2024)', 'Đun nước nhanh, an toàn.', 3463843),
    (gen_random_uuid(), 'Nón kết Adidas - Màu đen', 'Năng động, thể thao.', 4501886),
    (gen_random_uuid(), 'Dầu gội Head & Shoulders - Màu trắng', 'Sạch gàu, sảng khoái.', 915210),
    (gen_random_uuid(), 'Serum Estee Lauder Pro', 'Phục hồi da ban đêm thần kỳ.', 279196),
    (gen_random_uuid(), 'Bàn phím cơ Keychron Q1 Plus', 'Trải nghiệm gõ phím tuyệt vời cho lập trình viên.', 28664845),
    (gen_random_uuid(), 'Dầu ăn Simply 5L SE', 'Tốt cho tim mạch, không cholesterol.', 611343),
    (gen_random_uuid(), 'Bàn chải điện Oral-B Gen 2', 'Làm sạch răng hiệu quả.', 1505253),
    (gen_random_uuid(), 'iPad Pro M2 Gen 3', 'Màn hình Liquid Retina XDR sắc nét.', 19343553),
    (gen_random_uuid(), 'iPad Pro M2 #11', 'Màn hình Liquid Retina XDR sắc nét.', 42331546),
    (gen_random_uuid(), 'Serum Estee Lauder (Bản giới hạn) #12', 'Phục hồi da ban đêm thần kỳ.', 1979726),
    (gen_random_uuid(), 'Kem chống nắng La Roche-Posay (New 2024) #13', 'Bảo vệ da toàn diện dưới ánh nắng.', 1523327),
    (gen_random_uuid(), 'Serum Estee Lauder - Màu đen #14', 'Phục hồi da ban đêm thần kỳ.', 1675829),
    (gen_random_uuid(), 'Gạo ST25 đặc sản - Màu trắng #15', 'Gạo ngon nhất thế giới, thơm dẻo.', 330685),
    (gen_random_uuid(), 'Loa Marshall Emberton II Pro #16', 'Thiết kế cổ điển, âm thanh sống động.', 39911132),
    (gen_random_uuid(), 'Dầu ăn Simply 5L Plus #17', 'Tốt cho tim mạch, không cholesterol.', 202890),
    (gen_random_uuid(), 'Bánh trung thu Kinh Đô SE #18', 'Quà tặng ý nghĩa cho mùa trăng.', 849777),
    (gen_random_uuid(), 'Cà phê Trung Nguyên Sáng tạo Gen 2 #19', 'Khởi đầu ngày mới tỉnh táo.', 726326),
    (gen_random_uuid(), 'Máy sấy tóc Dyson Gen 3 #20', 'Sấy tóc nhanh, bảo vệ tóc bóng mượt.', 4535562),
    (gen_random_uuid(), 'Bộ nồi inox 304 #21', 'Chất liệu cao cấp, bền đẹp.', 9038195),
    (gen_random_uuid(), 'MacBook Air M3 (Bản giới hạn) #22', 'Mỏng nhẹ, hiệu năng vượt trội cho dân văn phòng.', 16678287),
    (gen_random_uuid(), 'Serum Estee Lauder (New 2024) #23', 'Phục hồi da ban đêm thần kỳ.', 699975),
    (gen_random_uuid(), 'Loa Marshall Emberton II - Màu đen #24', 'Thiết kế cổ điển, âm thanh sống động.', 37696944),
    (gen_random_uuid(), 'Bàn phím cơ Keychron Q1 - Màu trắng #25', 'Trải nghiệm gõ phím tuyệt vời cho lập trình viên.', 30605994),
    (gen_random_uuid(), 'Sữa tươi Vinamilk Pro #26', 'Bổ sung canxi và vitamin.', 757070),
    (gen_random_uuid(), 'Cà phê Trung Nguyên Sáng tạo Plus #27', 'Khởi đầu ngày mới tỉnh táo.', 143514),
    (gen_random_uuid(), 'Gạo ST25 đặc sản SE #28', 'Gạo ngon nhất thế giới, thơm dẻo.', 720731),
    (gen_random_uuid(), 'Chuột Logitech MX Master 3S Gen 2 #29', 'Thiết kế công thái học, cuộn siêu nhanh.', 20327045),
    (gen_random_uuid(), 'Gạo ST25 đặc sản Gen 3 #30', 'Gạo ngon nhất thế giới, thơm dẻo.', 345183),
    (gen_random_uuid(), 'Giày Nike Air Force 1 #31', 'Thiết kế trẻ trung, dễ phối đồ.', 3808029),
    (gen_random_uuid(), 'Váy hoa nhí nữ (Bản giới hạn) #32', 'Dễ thương, phong cách vintage.', 1629174),
    (gen_random_uuid(), 'Nước mắm Nam Ngư (New 2024) #33', 'Gia vị đậm đà cho món ăn Việt.', 303801),
    (gen_random_uuid(), 'Máy sấy tóc Dyson - Màu đen #34', 'Sấy tóc nhanh, bảo vệ tóc bóng mượt.', 782648),
    (gen_random_uuid(), 'Hạt điều rang muối - Màu trắng #35', 'Món ăn vặt bổ dưỡng, giòn tan.', 982126),
    (gen_random_uuid(), 'Quần Jeans Levi''s 501 Pro #36', 'Phong cách huyền thoại, bền bỉ theo thời gian.', 1120786),
    (gen_random_uuid(), 'iPad Pro M2 Plus #37', 'Màn hình Liquid Retina XDR sắc nét.', 27197959),
    (gen_random_uuid(), 'Tai nghe Sony WH-1000XM5 SE #38', 'Chống ồn đỉnh cao, âm thanh trung thực.', 25209117),
    (gen_random_uuid(), 'Hạt điều rang muối Gen 2 #39', 'Món ăn vặt bổ dưỡng, giòn tan.', 711019),
    (gen_random_uuid(), 'Gạo ST25 đặc sản Gen 3 #40', 'Gạo ngon nhất thế giới, thơm dẻo.', 975262),
    (gen_random_uuid(), 'Mắt kính Ray-Ban #41', 'Bảo vệ mắt tối ưu, phong cách thời thượng.', 2689453),
    (gen_random_uuid(), 'Bàn chải điện Oral-B (Bản giới hạn) #42', 'Làm sạch răng hiệu quả.', 973215),
    (gen_random_uuid(), 'Máy xay sinh tố Panasonic (New 2024) #43', 'Xay nhuyễn mọi loại trái cây.', 14661342),
    (gen_random_uuid(), 'Cà phê Trung Nguyên Sáng tạo - Màu đen #44', 'Khởi đầu ngày mới tỉnh táo.', 71684),
    (gen_random_uuid(), 'iPhone 15 Pro Max - Màu trắng #45', 'Siêu phẩm Apple với chip A17 Pro mạnh mẽ.', 26285277),
    (gen_random_uuid(), 'Nón kết Adidas Pro #46', 'Năng động, thể thao.', 937250),
    (gen_random_uuid(), 'Máy lọc không khí Xiaomi Plus #47', 'Loại bỏ bụi mịn PM2.5 hiệu quả.', 9586588),
    (gen_random_uuid(), 'Bánh trung thu Kinh Đô SE #48', 'Quà tặng ý nghĩa cho mùa trăng.', 206076),
    (gen_random_uuid(), 'Nồi chiên không dầu Philips Gen 2 #49', 'Nấu ăn ngon, giảm 80% dầu mỡ.', 5573524),
    (gen_random_uuid(), 'Đồng hồ Apple Watch Series 9 Gen 3 #50', 'Theo dõi sức khỏe và luyện tập chuyên nghiệp.', 27301450),
    (gen_random_uuid(), 'Nón kết Adidas #51', 'Năng động, thể thao.', 1363491),
    (gen_random_uuid(), 'iPad Pro M2 (Bản giới hạn) #52', 'Màn hình Liquid Retina XDR sắc nét.', 25875476),
    (gen_random_uuid(), 'Ví da cá sấu nam (New 2024) #53', 'Sang trọng, lịch lãm cho phái mạnh.', 835143),
    (gen_random_uuid(), 'Nước mắm Nam Ngư - Màu đen #54', 'Gia vị đậm đà cho món ăn Việt.', 643217),
    (gen_random_uuid(), 'Bàn là hơi nước Tefal - Màu trắng #55', 'Ủi quần áo phẳng phiu dễ dàng.', 9026538),
    (gen_random_uuid(), 'Ấm đun siêu tốc Electrolux Pro #56', 'Đun nước nhanh, an toàn.', 13813044),
    (gen_random_uuid(), 'Nước hoa Dior Sauvage Plus #57', 'Mùi hương nam tính, lôi cuốn.', 1785114),
    (gen_random_uuid(), 'Máy xay sinh tố Panasonic SE #58', 'Xay nhuyễn mọi loại trái cây.', 9621492),
    (gen_random_uuid(), 'Sữa tươi Vinamilk Gen 2 #59', 'Bổ sung canxi và vitamin.', 242100),
    (gen_random_uuid(), 'Thắt lưng da bò Gen 3 #60', 'Phụ kiện không thể thiếu cho quý ông.', 3883903),
    (gen_random_uuid(), 'Lò vi sóng Sharp #61', 'Hâm nóng thức ăn nhanh chóng.', 13146027),
    (gen_random_uuid(), 'Son môi MAC (Bản giới hạn) #62', 'Màu sắc chuẩn, lâu trôi.', 1660514),
    (gen_random_uuid(), 'Nồi chiên không dầu Philips (New 2024) #63', 'Nấu ăn ngon, giảm 80% dầu mỡ.', 12362933),
    (gen_random_uuid(), 'Trà xanh Thái Nguyên - Màu đen #64', 'Hương thơm nồng nàn, vị chát ngọt.', 70877),
    (gen_random_uuid(), 'Gạo ST25 đặc sản - Màu trắng #65', 'Gạo ngon nhất thế giới, thơm dẻo.', 147551),
    (gen_random_uuid(), 'Váy hoa nhí nữ Pro #66', 'Dễ thương, phong cách vintage.', 709202),
    (gen_random_uuid(), 'Thịt bò Mỹ nhập khẩu Plus #67', 'Thịt mềm, vân mỡ đều.', 858737),
    (gen_random_uuid(), 'Màn hình Dell UltraSharp 27 SE #68', 'Độ phân giải 4K, màu sắc chính xác.', 23531597),
    (gen_random_uuid(), 'Son môi MAC Gen 2 #69', 'Màu sắc chuẩn, lâu trôi.', 1633808),
    (gen_random_uuid(), 'Ấm đun siêu tốc Electrolux Gen 3 #70', 'Đun nước nhanh, an toàn.', 14845449),
    (gen_random_uuid(), 'Mắt kính Ray-Ban #71', 'Bảo vệ mắt tối ưu, phong cách thời thượng.', 2083613),
    (gen_random_uuid(), 'Kem chống nắng La Roche-Posay (Bản giới hạn) #72', 'Bảo vệ da toàn diện dưới ánh nắng.', 460328),
    (gen_random_uuid(), 'Bàn chải điện Oral-B (New 2024) #73', 'Làm sạch răng hiệu quả.', 1622948),
    (gen_random_uuid(), 'Lò vi sóng Sharp - Màu đen #74', 'Hâm nóng thức ăn nhanh chóng.', 6610316),
    (gen_random_uuid(), 'Hạt điều rang muối - Màu trắng #75', 'Món ăn vặt bổ dưỡng, giòn tan.', 296681),
    (gen_random_uuid(), 'Túi xách nữ Chanel Pro #76', 'Đẳng cấp thời trang thượng lưu.', 2117630),
    (gen_random_uuid(), 'Bánh trung thu Kinh Đô Plus #77', 'Quà tặng ý nghĩa cho mùa trăng.', 117414),
    (gen_random_uuid(), 'iPhone 15 Pro Max SE #78', 'Siêu phẩm Apple với chip A17 Pro mạnh mẽ.', 37963309),
    (gen_random_uuid(), 'Kem chống nắng La Roche-Posay Gen 2 #79', 'Bảo vệ da toàn diện dưới ánh nắng.', 2688180),
    (gen_random_uuid(), 'iPad Pro M2 Gen 3 #80', 'Màn hình Liquid Retina XDR sắc nét.', 28365804),
    (gen_random_uuid(), 'Bàn là hơi nước Tefal #81', 'Ủi quần áo phẳng phiu dễ dàng.', 14820941),
    (gen_random_uuid(), 'Tẩy trang Bioderma (Bản giới hạn) #82', 'Làm sạch sâu không gây kích ứng.', 1472696),
    (gen_random_uuid(), 'Son môi MAC (New 2024) #83', 'Màu sắc chuẩn, lâu trôi.', 761606),
    (gen_random_uuid(), 'iPad Pro M2 - Màu đen #84', 'Màn hình Liquid Retina XDR sắc nét.', 16255093),
    (gen_random_uuid(), 'MacBook Air M3 - Màu trắng #85', 'Mỏng nhẹ, hiệu năng vượt trội cho dân văn phòng.', 33977825),
    (gen_random_uuid(), 'Túi xách nữ Chanel Pro #86', 'Đẳng cấp thời trang thượng lưu.', 3945538),
    (gen_random_uuid(), 'Nước hoa Dior Sauvage Plus #87', 'Mùi hương nam tính, lôi cuốn.', 485065),
    (gen_random_uuid(), 'Máy lọc không khí Xiaomi SE #88', 'Loại bỏ bụi mịn PM2.5 hiệu quả.', 3041989),
    (gen_random_uuid(), 'Ví da cá sấu nam Gen 2 #89', 'Sang trọng, lịch lãm cho phái mạnh.', 4518592),
    (gen_random_uuid(), 'Sữa tươi Vinamilk Gen 3 #90', 'Bổ sung canxi và vitamin.', 617782),
    (gen_random_uuid(), 'Gạo ST25 đặc sản #91', 'Gạo ngon nhất thế giới, thơm dẻo.', 856651),
    (gen_random_uuid(), 'Nón kết Adidas (Bản giới hạn) #92', 'Năng động, thể thao.', 1598395),
    (gen_random_uuid(), 'Serum Estee Lauder (New 2024) #93', 'Phục hồi da ban đêm thần kỳ.', 666341),
    (gen_random_uuid(), 'Màn hình Dell UltraSharp 27 - Màu đen #94', 'Độ phân giải 4K, màu sắc chính xác.', 19314758),
    (gen_random_uuid(), 'Quần Jeans Levi''s 501 - Màu trắng #95', 'Phong cách huyền thoại, bền bỉ theo thời gian.', 1006828),
    (gen_random_uuid(), 'Váy hoa nhí nữ Pro #96', 'Dễ thương, phong cách vintage.', 2503872),
    (gen_random_uuid(), 'Tai nghe Sony WH-1000XM5 Plus #97', 'Chống ồn đỉnh cao, âm thanh trung thực.', 31813809),
    (gen_random_uuid(), 'Kem chống nắng La Roche-Posay SE #98', 'Bảo vệ da toàn diện dưới ánh nắng.', 1066344),
    (gen_random_uuid(), 'Nước hoa Dior Sauvage Gen 2 #99', 'Mùi hương nam tính, lôi cuốn.', 2057094),
    (gen_random_uuid(), 'Robot hút bụi Roborock Gen 3 #100', 'Tự động làm sạch nhà cửa thông minh.', 14294507)
ON CONFLICT DO NOTHING;